### ISSUE TITLE
Два поля models-list с одним классом моделей

### ISSUE THREAD

**Issue by verkholantsev** [bem/bem-mvc#134]
Правильно я понимаю, что в одной модели не может быть двух полей с одинаковым классом модели?

```
BEM.MODEL.decl('model', {
  field0: {
    type: 'models-list',
    name: 'submobel'
  },
  field1: {
    type: 'models-list',
    name: 'submobel'
}
```

Судя по тому, как формируется `eventPath` в `BEM.MODEL.on(...)`(https://github.com/bem/bem-mvc/blob/a25c19a7c9dd571fa9941b1c93e53e9822352b39/common.blocks/i-model/i-model.js#L748), этого не может быть by design?

**Comment by dosyara** [comment]
Да, есть такая проблема.
Это не бай дизайн, но очень технически обусловлено.

**Comment by verkholantsev** [comment]
То есть текущее решение — использовать разные классы моделей?

**Comment by dosyara** [comment]
Да, но вообще это можно починить.
