### ISSUE TITLE
Возможность создавать событие ошибки на поле модели

### ISSUE THREAD

**Issue by sullenor** [bem/bem-mvc#151]
Привет!

Я тут столкнулся с необходимость вручную генерировать ошибки на полях модели и чтобы не создавать велосипеды хочу использовать метод [_trigger()](https://github.com/bem/bem-mvc/blob/master/common.blocks/i-model/__field/i-model__field.js#L33) на полях модели публичным.

Что вы об этом думаете? Я готов прислать pr.

**Comment by dosyara** [comment]
А можешь подробней про свой случай рассказать.
Мы у себя в моделях пишем так:
``
this.trigger('store_content_href', 'error', { text: e.message });
``
Ты какой-то другой кейс хочешь упростить?

**Comment by sullenor** [comment]
Кажется твой вариант мне подойдет, надо попробовать :) Что-то я не подумал о таком применении.

А кейс следующий: у меня есть базовая моделька, у которой поле связано с инпутом и умеет валидировать пользовательский ввод. У нас для таких полей есть байндер *i-glue-field*, который слушает событие `error` на поле модели и показывает попапчик у контрола с текстом ошибки.
В силу обстоятельств данная моделька умеет еще и ходить на сервер, который выполняет какие-то действия. Если действия завершились ошибкой, хочется вручную создавать событие `error` с сообщением, которое пришло с сервера.

**Comment by sullenor** [comment]
Сережа, твой вариант у меня заработал! Спасибо :)
Думаю, тикет можно закрыть.

**Comment by dosyara** [comment]
Ok :)
