### ISSUE TITLE
i-bem__dom.js меняет стандартное поведение

### ISSUE THREAD

**Issue by kompolom** [bem/bem-mvc#171]
При использовании пакета с bem-core (v2.8) и bem-mvc (v2). Появляется следующая проблема:

```
var insertedDom = BEMDOM.append(node, htmlStr); //undefined
```

Методы изменяющие dom перестаю возвращать изменения. А это очень полезная фича. 
Нужно ли переопределение блока `i-bem__dom` на уровне `bem-mvc`?

**Comment by dosyara** [comment]
Ветка `v2` очень слабо поддерживается и bem-core очень далеко ушел вперед по сравнению с текущей версией в `v2`. Какое-то API может быть сломано.
Никаких специальных ограничений для bem-core со стороны bem-mvc я не помню, скорее всего это просто баг из-за разницы в версиях. 
Если есть возможность, присылайте PR с фиксом.

**Comment by tadatuta** [comment]
Насколько я вижу, должно быть достаточно просто добавить `return` перед https://github.com/bem/bem-mvc/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L12

**Comment by kompolom** [comment]
@dosyara Я бы прислал, но только начал разбираться с библиотекой. Пока не вник в зависимости и боюсь что мой PR больше сломает чем починит.
